/**
 * Danh sách 27 Giáo phận Công giáo tại Việt Nam và các Giáo hạt trực thuộc.
 * Dữ liệu được cấu trúc cố định vì cấu trúc hành chính giáo phận rất ít khi thay đổi (hàng thập kỷ).
 */
export const DIOCESES_DEANERIES_MAP: Record<string, string[]> = {
  'Tổng giáo phận Hà Nội': [
    'Giáo hạt Chính Tòa',
    'Giáo hạt Lý Nhân',
    'Giáo hạt Nam Định',
    'Giáo hạt Phú Xuyên',
    'Giáo hạt Thanh Oai',
    'Giáo hạt Mỹ Đức - Hòa Bình',
    'Giáo hạt Phủ Lý',
    'Giáo hạt Mỹ Lộc',
  ],
  'Tổng giáo phận Huế': [
    'Giáo hạt Thành phố Huế',
    'Giáo hạt Hải Lăng',
    'Giáo hạt Quảng Trị',
    'Giáo hạt Hương Phú',
    'Giáo hạt Hương Quảng',
  ],
  'Tổng giáo phận TP. Hồ Chí Minh': [
    'Giáo hạt Bình An',
    'Giáo hạt Chí Hòa',
    'Giáo hạt Gia Định',
    'Giáo hạt Gò Vấp',
    'Giáo hạt Hóc Môn',
    'Giáo hạt Phú Nhuận',
    'Giáo hạt Phú Thọ',
    'Giáo hạt Sài Gòn - Chợ Quán',
    'Giáo hạt Tân Định',
    'Giáo hạt Tân Sơn Nhì',
    'Giáo hạt Thủ Đức',
    'Giáo hạt Thủ Thiêm',
    'Giáo hạt Xóm Chiếu',
    'Giáo hạt Xóm Mới',
  ],
  'Giáo phận Bà Rịa': [
    'Giáo hạt Bà Rịa',
    'Giáo hạt Vũng Tàu',
    'Giáo hạt Bình Giã',
    'Giáo hạt Xuyên Mộc',
    'Giáo hạt Long Hương',
  ],
  'Giáo phận Bắc Ninh': [
    'Giáo hạt Bắc Ninh',
    'Giáo hạt Bắc Giang',
    'Giáo hạt Nội Bài',
    'Giáo hạt Thái Nguyên',
    'Giáo hạt Tuyên Quang',
    'Giáo hạt Vĩnh Phúc',
  ],
  'Giáo phận Ban Mê Thuột': [
    'Giáo hạt Ban Mê Thuột',
    'Giáo hạt Buôn Hồ',
    'Giáo hạt Gia Nghĩa',
    'Giáo hạt Phước Long',
    'Giáo hạt Đồng Xoài',
  ],
  'Giáo phận Bùi Chu': [
    'Giáo hạt Bùi Chu',
    'Giáo hạt Báo Đáp',
    'Giáo hạt Đại Đồng',
    'Giáo hạt Kiên Chính',
    'Giáo hạt Lạc Đạo',
    'Giáo hạt Liễu Đề',
    'Giáo hạt Ninh Cường',
    'Giáo hạt Phú Nhai',
    'Giáo hạt Quần Phương',
    'Giáo hạt Quỹ Nhất',
    'Giáo hạt Thức Hóa',
    'Giáo hạt Tứ Trùng',
    'Giáo hạt Tương Nam',
  ],
  'Giáo phận Cần Thơ': [
    'Giáo hạt Cần Thơ',
    'Giáo hạt Đại Hải',
    'Giáo hạt Trà Lồng',
    'Giáo hạt Vị Thanh',
    'Giáo hạt Sóc Trăng',
    'Giáo hạt Bạc Liêu',
    'Giáo hạt Cà Mau',
  ],
  'Giáo phận Đà Lạt': [
    'Giáo hạt Đà Lạt',
    'Giáo hạt Bảo Lộc',
    'Giáo hạt Đơn Dương',
    'Giáo hạt Đức Trọng',
    'Giáo hạt Đạ Tông',
    'Giáo hạt Di Linh',
  ],
  'Giáo phận Đà Nẵng': [
    'Giáo hạt Đà Nẵng',
    'Giáo hạt Hội An',
    'Giáo hạt Hòa Vang',
    'Giáo hạt Trà Kiệu',
    'Giáo hạt Tam Kỳ',
  ],
  'Giáo phận Hà Tĩnh': [
    'Giáo hạt Văn Hạnh',
    'Giáo hạt Cẩm Xuyên',
    'Giáo hạt Kỳ Anh',
    'Giáo hạt Bình An',
    'Giáo hạt Hương Phương',
    'Giáo hạt Ngàn Sâu',
    'Giáo hạt Ngàn Phố',
  ],
  'Giáo phận Hải Phòng': [
    'Giáo hạt Chính Tòa',
    'Giáo hạt Hải Dương',
    'Giáo hạt Hòn Gai',
    'Giáo hạt Kẻ Sặt',
    'Giáo hạt Mạo Khê',
    'Giáo hạt Nam Am',
  ],
  'Giáo phận Hưng Hóa': [
    'Giáo hạt Sơn Tây - Hòa Bình - Sơn La',
    'Giáo hạt Tây Bắc Phú Thọ',
    'Giáo hạt Tây Nam Phú Thọ',
    'Giáo hạt Lào Cai - Lai Châu - Điện Biên',
    'Giáo hạt Yên Bái',
    'Giáo hạt Hà Tuyên Hùng',
  ],
  'Giáo phận Kon Tum': [
    'Giáo hạt Kon Tum',
    'Giáo hạt Pleiku',
    'Giáo hạt Đăk Hà',
    'Giáo hạt Đăk Tô',
    'Giáo hạt Mang Yang',
  ],
  'Giáo phận Lạng Sơn và Cao Bằng': [
    'Giáo hạt Lạng Sơn',
    'Giáo hạt Cao Bằng',
    'Giáo hạt Thất Khê',
  ],
  'Giáo phận Long Xuyên': [
    'Giáo hạt Long Xuyên',
    'Giáo hạt Châu Đốc',
    'Giáo hạt Chợ Mới',
    'Giáo hạt Vĩnh An',
    'Giáo hạt Vĩnh Thạnh',
    'Giáo hạt Tân Thạnh',
    'Giáo hạt Tân Hiệp',
    'Giáo hạt Rạch Giá',
    'Giáo hạt Hà Tiên',
  ],
  'Giáo phận Mỹ Tho': [
    'Giáo hạt Mỹ Tho',
    'Giáo hạt Tân An',
    'Giáo hạt Cái Bè',
    'Giáo hạt Đức Hòa',
    'Giáo hạt Cao Lãnh',
    'Giáo hạt Cù Lao Tây',
  ],
  'Giáo phận Nha Trang': [
    'Giáo hạt Nha Trang',
    'Giáo hạt Cam Ranh',
    'Giáo hạt Ninh Hòa',
    'Giáo hạt Phan Rang',
    'Giáo hạt Diên Khánh',
    'Giáo hạt Vạn Ninh',
  ],
  'Giáo phận Phát Diệm': [
    'Giáo hạt Phát Diệm',
    'Giáo hạt Bạch Liên',
    'Giáo hạt Cách Tâm',
    'Giáo hạt Đồng Chưa',
    'Giáo hạt Ninh Bình',
    'Giáo hạt Phúc Nhạc',
    'Giáo hạt Tôn Đạo',
    'Giáo hạt Văn Hải',
    'Giáo hạt Vô Hốt',
  ],
  'Giáo phận Phan Thiết': [
    'Giáo hạt Phan Thiết',
    'Giáo hạt Hàm Tân',
    'Giáo hạt Hàm Thuận Nam',
    'Giáo hạt Hàm Thuận Bắc',
    'Giáo hạt Bắc Bình',
    'Giáo hạt Tánh Linh',
    'Giáo hạt Đức Linh',
  ],
  'Giáo phận Phú Cường': [
    'Giáo hạt Phú Cường',
    'Giáo hạt Bến Cát',
    'Giáo hạt Bình Long',
    'Giáo hạt Củ Chi',
    'Giáo hạt Lạc An',
    'Giáo hạt Phước Thành',
    'Giáo hạt Tây Ninh',
  ],
  'Giáo phận Qui Nhơn': [
    'Giáo hạt Qui Nhơn',
    'Giáo hạt Tuy Hòa',
    'Giáo hạt Bồng Sơn',
    'Giáo hạt Gò Thị',
    'Giáo hạt Mằng Lăng',
  ],
  'Giáo phận Thái Bình': [
    'Giáo hạt Thái Bình',
    'Giáo hạt Đông Hưng',
    'Giáo hạt Kiến Xương',
    'Giáo hạt Quỳnh Côi',
    'Giáo hạt Thái Thụy',
    'Giáo hạt Tiền Hải',
    'Giáo hạt Hưng Nhân',
    'Giáo hạt Tây Hưng Nhân',
  ],
  'Giáo phận Thanh Hóa': [
    'Giáo hạt Chính Tòa',
    'Giáo hạt Ba Làng',
    'Giáo hạt Nga Sơn',
    'Giáo hạt Vĩnh Lộc',
  ],
  'Giáo phận Vinh': [
    'Giáo hạt Chính Tòa',
    'Giáo hạt Cửa Lò',
    'Giáo hạt Bát Yên',
    'Giáo hạt Nhân Hòa',
    'Giáo hạt Thuận Nghĩa',
    'Giáo hạt Kẻ Dừa',
    'Giáo hạt Vàng Mai',
  ],
  'Giáo phận Vĩnh Long': [
    'Giáo hạt Vĩnh Long',
    'Giáo hạt Bến Tre',
    'Giáo hạt Cái Mơn',
    'Giáo hạt Trà Vinh',
    'Giáo hạt Vũng Liêm',
  ],
  'Giáo phận Xuân Lộc': [
    'Giáo hạt An Bình',
    'Giáo hạt Biên Hòa',
    'Giáo hạt Gia Kiệm',
    'Giáo hạt Gia Ray',
    'Giáo hạt Hòa Thanh',
    'Giáo hạt Hố Nai',
    'Giáo hạt Long Khánh',
    'Giáo hạt Long Thành',
    'Giáo hạt Phương Lâm',
    'Giáo hạt Phú Thịnh',
    'Giáo hạt Phước Lý',
    'Giáo hạt Tân Mai',
    'Giáo hạt Túc Trưng',
  ],
};

export const DIOCESES_LIST = Object.keys(DIOCESES_DEANERIES_MAP);
